# Import MNIST data set

In [108]:
import tensorflow as tf
import pickle
import os
from datetime import datetime

mnist = tf.keras.datasets.mnist;

DATASET_PATH = os.path.join("datasets", "mnist");
ROOT_LOG_DIR = 'tf_logs'

def load_dataset(dataset_path=DATASET_PATH):
    if not os.path.isdir(dataset_path):
        os.makedirs(dataset_path)
        print('Creating folders....')
        (x_train, y_train), (x_test, y_test) = mnist.load_data()
        with open(os.path.join(dataset_path,'x_train.pickle'), 'wb') as handle:
            pickle.dump(x_train, handle, protocol=pickle.HIGHEST_PROTOCOL)
        with open(os.path.join(dataset_path,'y_train.pickle'), 'wb') as handle:
            pickle.dump(y_train, handle, protocol=pickle.HIGHEST_PROTOCOL)
        with open(os.path.join(dataset_path,'x_test.pickle'), 'wb') as handle:
            pickle.dump(x_test, handle, protocol=pickle.HIGHEST_PROTOCOL)
        with open(os.path.join(dataset_path,'y_test.pickle'), 'wb') as handle:
            pickle.dump(y_test, handle, protocol=pickle.HIGHEST_PROTOCOL)
    else:
        print('Folders exist. Collecting datasets...')
        with open(os.path.join(dataset_path,'x_train.pickle'), 'rb') as handle:
            x_train= pickle.load(handle)
        with open(os.path.join(dataset_path,'y_train.pickle'), 'rb') as handle:
             y_train= pickle.load(handle)
        with open(os.path.join(dataset_path,'x_test.pickle'), 'rb') as handle:
             x_test = pickle.load(handle)
        with open(os.path.join(dataset_path,'y_test.pickle'), 'rb') as handle:
             y_test = pickle.load(handle)
    print('datasets fetched.')

load_dataset()

Folders exist. Collecting datasets...
datasets fetched.


In [168]:
from tensorflow.keras.layers import Dense, Conv2D, Flatten, LeakyReLU, MaxPooling2D
from tensorflow.keras.models import Sequential
from tensorflow.keras.activations import sigmoid
from tensorflow.keras.utils import to_categorical

In [192]:
num_filter = 8

model = Sequential()
model.add(
        Conv2D(num_filter,
                 kernel_size=4,
                 strides=(1,1),
                 input_shape=[28,28,1],
                 activation=LeakyReLU(),
                 padding='same',
                )
         )

model.add(MaxPooling2D(pool_size=(2,2), padding='same', strides=(1,1)))
model.add(
        Conv2D(num_filter,
                 kernel_size=4,
                 strides=(2,2),
                 activation=LeakyReLU(),
                 padding='same',
                )
         )
model.add(MaxPooling2D(pool_size=(2,2), padding='valid', strides=(2,2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_25 (Conv2D)           (None, 28, 28, 8)         136       
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 28, 28, 8)         0         
_________________________________________________________________
conv2d_26 (Conv2D)           (None, 14, 14, 8)         1032      
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 7, 7, 8)           0         
_________________________________________________________________
flatten_21 (Flatten)         (None, 392)               0         
_________________________________________________________________
dense_26 (Dense)             (None, 128)               50304     
_________________________________________________________________
dense_27 (Dense)             (None, 10)                1290      
Total para

## Check input sample shape

In [193]:
x_train.shape

(60000, 28, 28)

In [194]:
X = x_train.reshape((60000,28,28,1))

In [195]:

Y = to_categorical(
    y_train,
    num_classes=10
)
map_test = [val for val in zip(Y[0:10],y_train[0:10])]
for val in map_test:
    print(val)


(array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32), 5)
(array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32), 0)
(array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32), 4)
(array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32), 1)
(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32), 9)
(array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.], dtype=float32), 2)
(array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32), 1)
(array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32), 3)
(array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32), 1)
(array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32), 4)


In [196]:
now = datetime.utcnow().strftime('%Y%m%d%H%M%S')
logdir = "{}/run-{}".format(ROOT_LOG_DIR, now)

In [197]:
model.fit(X, Y, epochs=10, batch_size=32)

Epoch 1/10
60000/60000 [==============================] - 25s 421us/step - loss: 0.9639 - acc: 0.9058
Epoch 2/10
60000/60000 [==============================] - 25s 408us/step - loss: 0.0790 - acc: 0.9775
Epoch 3/10
60000/60000 [==============================] - 24s 407us/step - loss: 0.0621 - acc: 0.9816
Epoch 4/10
60000/60000 [==============================] - 25s 419us/step - loss: 0.0566 - acc: 0.9836
Epoch 5/10
60000/60000 [==============================] - 25s 417us/step - loss: 0.0467 - acc: 0.9865
Epoch 6/10
60000/60000 [==============================] - 25s 410us/step - loss: 0.0461 - acc: 0.9867
Epoch 7/10
60000/60000 [==============================] - 24s 408us/step - loss: 0.0394 - acc: 0.9885
Epoch 8/10
60000/60000 [==============================] - 25s 412us/step - loss: 0.0375 - acc: 0.9896
Epoch 9/10
60000/60000 [==============================] - 25s 410us/step - loss: 0.0379 - acc: 0.9901
Epoch 10/10
60000/60000 [==============================] - 25s 412us/step - loss: 

In [198]:
from sklearn.metrics import accuracy_score
X_TEST = x_test.reshape((10000,28,28,1))
y_pred = model.predict(X_TEST)

In [199]:
y_pred = np.argmax(y_pred, axis=1)
y_pred

array([7, 2, 1, ..., 4, 5, 6])

In [200]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [201]:
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.9803
